### ISSUE TITLE
Did you miss these?

### ISSUE THREAD

**Issue by johndpope** [nubbel/swift-tensorflow#1]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/protobuf
![screen shot 2016-11-03 at 12 24 19](https://cloud.githubusercontent.com/assets/289994/19974865/53fb32e8-a1c0-11e6-8634-750ab6fdc3d6.png)

**Comment by nubbel** [comment]
@johndpope Good catch! I added the remaining protos in the last commit.

**Comment by johndpope** [comment]
thanks
