### ISSUE TITLE
TODO - build out inception example to talk to tensorflow

### ISSUE THREAD

**Issue by johndpope** [nubbel/swift-tensorflow#8]
There is this docker file we can use as the server.

https://github.com/johndpope/tensorflow-grpc-swift

**Comment by johndpope** [comment]
the inception docker container is correctly connecting.

**Comment by johndpope** [comment]
<img width="1380" alt="screen shot 2017-04-29 at 12 32 04" src="https://cloud.githubusercontent.com/assets/289994/25557090/f000e06e-2cd7-11e7-8f5f-168ca68b972d.png">

I dropped in the java references. 

TODO - 

port the java class over to swift

https://github.com/thammegowda/tensorflow-grpc-java
this app has following logic backed by a couple of classes around grpc 


 public static final class **InceptionRequest** extends GeneratedMessage implements


public class **InceptionBlockingStub** extends AbstractStub<InceptionBlockingStub> 


code we want to port to run in appdelegate

```

 if (args.length != 2){
      System.out.println("Invalid args");
      System.out.println("Usage: <host:port> <image>");
      System.out.println("\tExample: localhost:9090 ~/Pictures/cat.jpg");
      System.exit(1);
    }

    String[] parts = args[0].split(":");
    String server = parts[0];
    int port = Integer.parseInt(parts[1]);
    String imagePath = args[1];

    TensorflowObjectRecogniser recogniser = new TensorflowObjectRecogniser(server, port);

    System.out.println("Image = " + imagePath);
    InputStream jpegStream = new FileInputStream(imagePath);
    List<Map.Entry<String, Double>> list = recogniser
        .recognise(jpegStream);
    System.out.println(list);
    recogniser.close();
    jpegStream.close();
```


N.B. all the tensorflow serving classes have been generated.

eg.Tensorflow_Serving_Class


<img width="1366" alt="screen shot 2017-04-29 at 12 39 39" src="https://cloud.githubusercontent.com/assets/289994/25557131/e32493e4-2cd8-11e7-8893-cb0b160f4c96.png">


I also generated all the javaGenerated classes so we maybe able to glue the inception reference code together.

**Comment by johndpope** [comment]
hi @thammegowda - any interest in helping out getting a swift hello world tensorflow project up and running?

**Comment by johndpope** [comment]
so running the java sample with a dropped in example.jpg works great.

![example](https://cloud.githubusercontent.com/assets/289994/25557227/726f8994-2cdb-11e7-857c-1f6d215a8017.jpg)


```
# pull and start the prebuilt container, forward port 9000
docker run -it -p 9000:9000 tgowda/inception_serving_tika

# Inside the container, start tensorflow service
root@8311ea4e8074:/# /serving/server.sh


```

 **mvn clean compile exec:java -Dexec.args="localhost:9000 example.jpg"**
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building tensorflow-java 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tensorflow-java ---
[INFO] Deleting /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow-grpc-java/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tensorflow-java ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ tensorflow-java ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 4 source files to /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow-grpc-java/target/classes
[WARNING] /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow-grpc-java/src/main/java/edu/usc/irds/tensorflow/grpc/InceptionInference.java: /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow-grpc-java/src/main/java/edu/usc/irds/tensorflow/grpc/InceptionInference.java uses or overrides a deprecated API.
[WARNING] /Users/johndpope/Documents/tensorFlowWorkspace/tensorflow-grpc-java/src/main/java/edu/usc/irds/tensorflow/grpc/InceptionInference.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ tensorflow-java ---
2017-04-29 12:56:22 DEBUG TensorflowObjectRecogniser:46 - Creating channel host:localhost, port=9000
Apr 29, 2017 12:56:22 PM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@646c54de] Created with target localhost:9000
Image = example.jpg
2017-04-29 12:56:24 DEBUG TensorflowObjectRecogniser:69 - Time taken : 1408ms
**[partridge=5.741777420043945, hen=5.065821170806885, goose=4.73418664932251, ruffed grouse, partridge, Bonasa umbellus=4.19035005569458, quail=3.59564208984375]**
2017-04-29 12:56:24 DEBUG TensorflowObjectRecogniser:84 - Closing the channel
Apr 29, 2017 12:56:24 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@646c54de] Terminated
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.765 s
[INFO] Finished at: 2017-04-29T12:56:27-04:00
[INFO] Final Memory: 19M/176M
[INFO] ---------------------------------------

**Comment by thammegowda** [comment]
@johndpope Wish I could help but I never written a single line of swift code (and now its not my priority to learn it, sorry)

However, speaking in abstract terms, here is what you need to do:

1. Get the proto files for the remote procedures 
 you are going to use: https://github.com/tensorflow/serving/tree/master/tensorflow_serving/apis . I had used `inception.proto`  may be a lot has been changed in recent days.

2. use the protoc to generate swift code for the proto files. 
3.  Create  a stub/wrapper  for it as per swift examples: https://github.com/grpc/grpc-swift/tree/master/Examples There were two ways in java - synchronous/blocking and asynchronous/callback - in my java code I used blocking/synchronous. Pick the one you need!


---
If you want to know how the docker image was built: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_inception.md

**Comment by johndpope** [comment]
thanks @thammegowda  - should be plug and play then with the respective proto file. 
seems to have gone missing from official repos.
https://github.com/tensorflow/serving/issues/425

**Comment by johndpope** [comment]
thanks again @thammegowda  - working.
